#docker-compose up -d
version: "3.7"

services:
  mvn:
    image: maven:3.9.3-ibm-semeru-17-focal
    container_name: jdkmvn
    environment:
      SERVER_PORT: 8080
    working_dir: /app
    volumes:
      - $PWD:/app
      - $HOME/uzrnem/maven:/root/.m2
    command: tail -f /dev/null #mvn spring-boot:run #
    ports:
      - 8080:8080